/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AnchorImport } from './routes/anchor'
import { Route as PathlessLayoutImport } from './routes/_pathlessLayout'
import { Route as PostsRouteImport } from './routes/posts.route'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts.index'
import { Route as PostsPostIdImport } from './routes/posts.$postId'
import { Route as PathlessLayoutNestedLayoutImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PostIdPostPathlessLayoutImport } from './routes/$postId/_postPathlessLayout'
import { Route as PostIdPostPathlessLayoutIndexImport } from './routes/$postId/_postPathlessLayout/index'
import { Route as PathlessLayoutNestedLayoutRouteBImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteAImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as PostIdPostPathlessLayoutWorksImport } from './routes/$postId/_postPathlessLayout/works'

// Create Virtual Routes

const PostIdImport = createFileRoute('/$postId')()

// Create/Update Routes

const PostIdRoute = PostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => rootRoute,
} as any)

const AnchorRoute = AnchorImport.update({
  id: '/anchor',
  path: '/anchor',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutRoute = PathlessLayoutImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const PostsRouteRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)

const PathlessLayoutNestedLayoutRoute = PathlessLayoutNestedLayoutImport.update(
  {
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any,
)

const PostIdPostPathlessLayoutRoute = PostIdPostPathlessLayoutImport.update({
  id: '/_postPathlessLayout',
  getParentRoute: () => PostIdRoute,
} as any)

const PostIdPostPathlessLayoutIndexRoute =
  PostIdPostPathlessLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PostIdPostPathlessLayoutRoute,
  } as any)

const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteAImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

const PostIdPostPathlessLayoutWorksRoute =
  PostIdPostPathlessLayoutWorksImport.update({
    id: '/works',
    path: '/works',
    getParentRoute: () => PostIdPostPathlessLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutImport
      parentRoute: typeof rootRoute
    }
    '/anchor': {
      id: '/anchor'
      path: '/anchor'
      fullPath: '/anchor'
      preLoaderRoute: typeof AnchorImport
      parentRoute: typeof rootRoute
    }
    '/$postId': {
      id: '/$postId'
      path: '/$postId'
      fullPath: '/$postId'
      preLoaderRoute: typeof PostIdImport
      parentRoute: typeof rootRoute
    }
    '/$postId/_postPathlessLayout': {
      id: '/$postId/_postPathlessLayout'
      path: '/$postId'
      fullPath: '/$postId'
      preLoaderRoute: typeof PostIdPostPathlessLayoutImport
      parentRoute: typeof PostIdRoute
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutImport
      parentRoute: typeof PathlessLayoutImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof PostsRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof PostsRouteImport
    }
    '/$postId/_postPathlessLayout/works': {
      id: '/$postId/_postPathlessLayout/works'
      path: '/works'
      fullPath: '/$postId/works'
      preLoaderRoute: typeof PostIdPostPathlessLayoutWorksImport
      parentRoute: typeof PostIdPostPathlessLayoutImport
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteAImport
      parentRoute: typeof PathlessLayoutNestedLayoutImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBImport
      parentRoute: typeof PathlessLayoutNestedLayoutImport
    }
    '/$postId/_postPathlessLayout/': {
      id: '/$postId/_postPathlessLayout/'
      path: '/'
      fullPath: '/$postId/'
      preLoaderRoute: typeof PostIdPostPathlessLayoutIndexImport
      parentRoute: typeof PostIdPostPathlessLayoutImport
    }
  }
}

// Create and export the route tree

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostIdPostPathlessLayoutRouteChildren {
  PostIdPostPathlessLayoutWorksRoute: typeof PostIdPostPathlessLayoutWorksRoute
  PostIdPostPathlessLayoutIndexRoute: typeof PostIdPostPathlessLayoutIndexRoute
}

const PostIdPostPathlessLayoutRouteChildren: PostIdPostPathlessLayoutRouteChildren =
  {
    PostIdPostPathlessLayoutWorksRoute: PostIdPostPathlessLayoutWorksRoute,
    PostIdPostPathlessLayoutIndexRoute: PostIdPostPathlessLayoutIndexRoute,
  }

const PostIdPostPathlessLayoutRouteWithChildren =
  PostIdPostPathlessLayoutRoute._addFileChildren(
    PostIdPostPathlessLayoutRouteChildren,
  )

interface PostIdRouteChildren {
  PostIdPostPathlessLayoutRoute: typeof PostIdPostPathlessLayoutRouteWithChildren
}

const PostIdRouteChildren: PostIdRouteChildren = {
  PostIdPostPathlessLayoutRoute: PostIdPostPathlessLayoutRouteWithChildren,
}

const PostIdRouteWithChildren =
  PostIdRoute._addFileChildren(PostIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/anchor': typeof AnchorRoute
  '/$postId': typeof PostIdPostPathlessLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/$postId/works': typeof PostIdPostPathlessLayoutWorksRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/$postId/': typeof PostIdPostPathlessLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/anchor': typeof AnchorRoute
  '/$postId': typeof PostIdPostPathlessLayoutIndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/$postId/works': typeof PostIdPostPathlessLayoutWorksRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/anchor': typeof AnchorRoute
  '/$postId': typeof PostIdRouteWithChildren
  '/$postId/_postPathlessLayout': typeof PostIdPostPathlessLayoutRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/$postId/_postPathlessLayout/works': typeof PostIdPostPathlessLayoutWorksRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/$postId/_postPathlessLayout/': typeof PostIdPostPathlessLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | ''
    | '/anchor'
    | '/$postId'
    | '/posts/$postId'
    | '/posts/'
    | '/$postId/works'
    | '/route-a'
    | '/route-b'
    | '/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/anchor'
    | '/$postId'
    | '/posts/$postId'
    | '/posts'
    | '/$postId/works'
    | '/route-a'
    | '/route-b'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_pathlessLayout'
    | '/anchor'
    | '/$postId'
    | '/$postId/_postPathlessLayout'
    | '/_pathlessLayout/_nested-layout'
    | '/posts/$postId'
    | '/posts/'
    | '/$postId/_postPathlessLayout/works'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/$postId/_postPathlessLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AnchorRoute: typeof AnchorRoute
  PostIdRoute: typeof PostIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AnchorRoute: AnchorRoute,
  PostIdRoute: PostIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts",
        "/_pathlessLayout",
        "/anchor",
        "/$postId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts": {
      "filePath": "posts.route.tsx",
      "children": [
        "/posts/$postId",
        "/posts/"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout.tsx",
      "children": [
        "/_pathlessLayout/_nested-layout"
      ]
    },
    "/anchor": {
      "filePath": "anchor.tsx"
    },
    "/$postId": {
      "filePath": "$postId",
      "children": [
        "/$postId/_postPathlessLayout"
      ]
    },
    "/$postId/_postPathlessLayout": {
      "filePath": "$postId/_postPathlessLayout.tsx",
      "parent": "/$postId",
      "children": [
        "/$postId/_postPathlessLayout/works",
        "/$postId/_postPathlessLayout/"
      ]
    },
    "/_pathlessLayout/_nested-layout": {
      "filePath": "_pathlessLayout/_nested-layout.tsx",
      "parent": "/_pathlessLayout",
      "children": [
        "/_pathlessLayout/_nested-layout/route-a",
        "/_pathlessLayout/_nested-layout/route-b"
      ]
    },
    "/posts/$postId": {
      "filePath": "posts.$postId.tsx",
      "parent": "/posts"
    },
    "/posts/": {
      "filePath": "posts.index.tsx",
      "parent": "/posts"
    },
    "/$postId/_postPathlessLayout/works": {
      "filePath": "$postId/_postPathlessLayout/works.tsx",
      "parent": "/$postId/_postPathlessLayout"
    },
    "/_pathlessLayout/_nested-layout/route-a": {
      "filePath": "_pathlessLayout/_nested-layout/route-a.tsx",
      "parent": "/_pathlessLayout/_nested-layout"
    },
    "/_pathlessLayout/_nested-layout/route-b": {
      "filePath": "_pathlessLayout/_nested-layout/route-b.tsx",
      "parent": "/_pathlessLayout/_nested-layout"
    },
    "/$postId/_postPathlessLayout/": {
      "filePath": "$postId/_postPathlessLayout/index.tsx",
      "parent": "/$postId/_postPathlessLayout"
    }
  }
}
ROUTE_MANIFEST_END */
